"""Мост WSL → Windows: команды `vydra` и `выдра` прямо в PowerShell и cmd.

В %LOCALAPPDATA%\\vydra\\bin кладутся vydra.ps1 / выдра.ps1 (PowerShell находит их раньше .cmd,
поэтому ссылки с «&» уходят в WSL как есть) и vydra.cmd / выдра.cmd для cmd.exe. Папка
добавляется в пользовательский PATH. Тела файлов — только ASCII: PowerShell 5.1 читает .ps1
без BOM в ANSI, а cmd — .cmd в OEM-кодировке. Там же — умные ссылки и Tab для PowerShell.
"""

from __future__ import annotations

import os
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

from . import shell, system

NAMES = ("vydra", "выдра")
MARK = "# vydra: WSL bridge (generated by `vydra bridge`)"


class BridgeError(Exception):
    pass


@dataclass
class Status:
    supported: bool
    files: bool = False
    on_path: bool = False
    policy: str | None = None  # эффективная ExecutionPolicy PowerShell
    folder: Path | None = None

    @property
    def scripts_allowed(self) -> bool:
        return (self.policy or "").lower() not in ("restricted", "allsigned")

    @property
    def ok(self) -> bool:
        return self.files and self.on_path


def launcher() -> Path:
    """Запускалка выдры внутри WSL: из того же окружения, что и этот процесс."""
    sibling = Path(sys.executable).with_name("vydra")
    if sibling.is_file():
        return sibling
    found = shutil.which("vydra")
    if found:
        return Path(found)
    raise BridgeError("Не нашёл команду vydra в WSL — переустановите выдру")


def distro() -> str:
    name = os.environ.get("WSL_DISTRO_NAME", "")
    if not name:
        raise BridgeError("Не удалось определить дистрибутив WSL (нет WSL_DISTRO_NAME)")
    return name


def windows_folder() -> Path:
    local = system.powershell("[Console]::Out.Write($env:LOCALAPPDATA)")
    path = system.from_windows(local) if local else None
    if path is None:
        raise BridgeError("Не удалось найти %LOCALAPPDATA% — проверьте, что в WSL включён interop")
    return path / "vydra" / "bin"


def ps1_text(distro_name: str, program: Path) -> str:
    lines = [
        MARK,
        "$vars = '_VYDRA_COMPLETE', '_TYPER_COMPLETE_ARGS', '_TYPER_COMPLETE_WORD_TO_COMPLETE'",
        "if ($env:_VYDRA_COMPLETE) {",
        "    $env:WSLENV = ((@($vars) + @($env:WSLENV -split ':' | Where-Object { $_ })) | Select-Object -Unique) -join ':'",
        "}",
        "$cwd = (Get-Location -PSProvider FileSystem).ProviderPath",
        f"& wsl.exe -d {distro_name} --cd $cwd -e {program} @args",
        "exit $LASTEXITCODE",
    ]
    return "\r\n".join(lines) + "\r\n"


def cmd_text(distro_name: str, program: Path) -> str:
    return "\r\n".join(["@echo off", f'wsl.exe -d {distro_name} --cd "%CD%\\." -e {program} %*']) + "\r\n"


def execution_policy() -> str | None:
    return system.powershell("[Console]::Out.Write((Get-ExecutionPolicy).ToString())")


def install(folder: Path | None = None, add_to_path: bool = True, profile: bool = True) -> list[str]:
    if system.OS != "wsl":
        raise BridgeError("Мост нужен только в WSL: в Windows, macOS и Linux команды vydra и выдра есть и так")
    name, program = distro(), launcher()
    for value in (name, str(program)):
        if not value.isascii() or " " in value:
            raise BridgeError(f"Путь «{value}» содержит пробелы или не-ASCII символы — мост его не поддерживает")
    folder = folder or windows_folder()
    folder.mkdir(parents=True, exist_ok=True)
    policy = execution_policy()
    scripts_ok = (policy or "").lower() not in ("restricted", "allsigned")
    messages = []
    for command in NAMES:
        (folder / f"{command}.cmd").write_bytes(cmd_text(name, program).encode("ascii"))
        ps1 = folder / f"{command}.ps1"
        if scripts_ok:
            ps1.write_bytes(ps1_text(name, program).encode("ascii"))
        else:
            ps1.unlink(missing_ok=True)  # при запрете скриптов PowerShell споткнулся бы о .ps1 — пусть берёт .cmd
    messages.append(f"Команды vydra и выдра: {system.display_path(folder)}")
    if add_to_path:
        messages.append(_add_to_user_path(folder))
    if profile and scripts_ok:
        messages += _install_powershell_integration(folder.parent / "shell" / "vydra.ps1")
    if not scripts_ok:
        messages.append(
            f"PowerShell запрещает скрипты (политика {policy}) — ссылки с & берите в кавычки или копируйте в буфер. "
            "Разрешить: Set-ExecutionPolicy -Scope CurrentUser RemoteSigned"
        )
    return messages


def uninstall(folder: Path | None = None) -> list[str]:
    folder = folder or windows_folder()
    removed = []
    for command in NAMES:
        for ext in ("ps1", "cmd"):
            path = folder / f"{command}.{ext}"
            if path.exists():
                path.unlink()
                removed.append(path.name)
    for profile, _policy in shell.powershell_profiles():
        shell._remove_block(profile)
    (folder.parent / "shell" / "vydra.ps1").unlink(missing_ok=True)
    win = system.to_windows(folder)
    if win:
        system.powershell(_path_script(win, remove=True))
    return removed


def status(folder: Path | None = None) -> Status:
    if system.OS != "wsl":
        return Status(supported=False)
    try:
        folder = folder or windows_folder()
    except BridgeError:
        return Status(supported=True)
    files = all((folder / f"{n}.cmd").is_file() for n in NAMES)
    win = system.to_windows(folder)
    on_path = bool(win) and system.powershell(_path_script(win, check=True)) == "present"
    return Status(supported=True, files=files, on_path=on_path, policy=execution_policy(), folder=folder)


def _path_script(win_dir: str, remove: bool = False, check: bool = False) -> str:
    literal = win_dir.replace("'", "''")
    head = f"""
$dir = '{literal}'
$key = 'HKCU:\\Environment'
$current = (Get-Item -Path $key).GetValue('Path', '', 'DoNotExpandEnvironmentNames')
$parts = @($current -split ';' | Where-Object {{ $_ }})
$has = @($parts | Where-Object {{ $_.TrimEnd('\\') -ieq $dir.TrimEnd('\\') }}).Count -gt 0
"""
    if check:
        return head + "[Console]::Out.Write($(if ($has) { 'present' } else { 'absent' }))"
    if remove:
        change = "$new = (@($parts | Where-Object { $_.TrimEnd('\\') -ine $dir.TrimEnd('\\') })) -join ';'"
        condition = "$has"
    else:
        change = "$new = (@($parts) + $dir) -join ';'"
        condition = "-not $has"
    # ExpandString — чтобы не сломать %USERPROFILE% и прочие переменные в PATH;
    # временная переменная окружения рассылает WM_SETTINGCHANGE — новые окна увидят PATH сразу
    return head + f"""
if ({condition}) {{
    {change}
    Set-ItemProperty -Path $key -Name Path -Value $new -Type ExpandString
    [Environment]::SetEnvironmentVariable('VYDRA_PATH_REFRESH', '1', 'User')
    [Environment]::SetEnvironmentVariable('VYDRA_PATH_REFRESH', $null, 'User')
    [Console]::Out.Write('changed')
}} else {{ [Console]::Out.Write('unchanged') }}
"""


def _add_to_user_path(folder: Path) -> str:
    win = system.to_windows(folder)
    if not win:
        raise BridgeError("Не удалось получить путь Windows для папки моста")
    result = system.powershell(_path_script(win))
    if result == "changed":
        return "Папка добавлена в PATH — откройте новое окно PowerShell или cmd"
    if result == "unchanged":
        return "Папка уже в PATH"
    raise BridgeError("Не удалось обновить PATH пользователя")


def _install_powershell_integration(script_path: Path) -> list[str]:
    script_path.parent.mkdir(parents=True, exist_ok=True)
    script_path.write_bytes(shell.script("powershell").replace("\n", "\r\n").encode("ascii"))
    target = shell.Target("powershell", script_path, None)
    done = []
    for profile, policy in shell.powershell_profiles():
        if not shell.scripts_allowed(policy):  # профиль с нашей строкой — красная ошибка в каждом окне
            if shell._remove_block(profile) and not shell._read(profile).strip():
                profile.unlink(missing_ok=True)
            continue
        target.rc = profile
        shell._write_block(profile, shell.block(target), powershell=True)
        done.append(f"Tab и умные ссылки в PowerShell: {system.display_path(profile)}")
    return done
